--- # 优先次序高
CHATROOM:
  SOCKET:
    HOST: 'chat.wjchat.com'
  STORAGE:
    HOST: 'chat.wjchat.com'
  HTTP:
    HOST: 'chat.wjchat.com'
  NGINX:
    CONFS:
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_socket_backend-socketio/public'
        SERVER_NAME: 'chat.wjchat.com'
        INDEX: 'index.html index.htm'
        # TRY_FILES: '$uri $uri/ /index.php?$query_string'
        PROXY_PASS: 'http://127.0.0.1:4003/'
        # ADD_HEADERS:
#           - "Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS'"
#           - "Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"
# 

      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_other_backend-koa/public'
        SERVER_NAME: 'chat.wjchat.com'
        INDEX: 'index.html index.htm'
        # TRY_FILES: '$uri $uri/ /index.php?$query_string'
        PROXY_PASS: 'http://127.0.0.1:4002'
        # ADD_HEADERS:
#           - "Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS'"
#           - "Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"
# 
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_any_frontend-vue/dist'
        SERVER_NAME: 'chat.wjchat.com'
        INDEX: 'index.html index.htm'
        TRY_FILES: '$uri $uri/ /index.html'
        
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-admin_any_backend-fastadmin/public'
        SERVER_NAME: 'chat.wjchat.com'
        INDEX: 'index.php index.html index.htm'
        # TRY_FILES: '$uri $uri/ /index.php?$query_string'
        PHP_VERSION: '7.3'
  MYSQL:
    HOST: '127.0.0.1'
    PORT: 3306
    DATABASE: 'chatroom'
    USERNAME: 'backend'
    PASSWORD: 'mysql_pass_backend'
  MONGODB:
    HOST: '127.0.0.1'
    PORT: 27017
    DATABASE: 'chatroom'
    USERNAME: 'backend'
    PASSWORD: 'mongodb_pass_backend'
  DRIVERS:
    ONE:
      LOGIN_STATE_URL: 'http://test.c368.com/apiapp/5d1cb62aa5488'
      MONEY_STATE_URL: 'http://test.c368.com/apiapp/5d1cb646059d8'