---
NDB:
  SERVERS:
    - HOST: '10.0.0.181'
      PORT: 3306
      DATADIR: '/var/lib/mysql'
      BASEDIR: '/var/lib/mysql'
      SOCKET: '/var/lib/mysql/mysql.sock'
    - HOST: '10.0.0.182'
      PORT: 3306
      DATADIR: '/var/lib/mysql'
      BASEDIR: '/var/lib/mysql'
      SOCKET: '/var/lib/mysql/mysql.sock'