---
- name: (template) scp /etc/filebeat/filebeat.yml.j2 /etc/filebeat/filebeat.yml
  template:
    src: etc/filebeat/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: vagrant
    group: vagrant
    mode: 0766