---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
- name: (yum )yum remove redis
  yum:
    name: redis
    state: absent
    
- name: (yum) yum install redis
  yum:
    name: redis
    state: present
  notify: debug yum install redis