---
- name: (yum) yum remove golang
  yum: 
    name:
      - golang
    state: absent
    
- name: (yum) yum install golang
  yum: 
    name:
      - golang
    state: latest
  notify: debug yum install golang
