---
- name: "(git) git clone git@github.com:landan789/cms-service_admin_backend-scms.git"
  git:
    repo: 'git@github.com:landan789/cms-service_admin_backend-scms.git'
    dest: "{{ DEST }}"
    version: "{{ 'develop' if branch == 'feature' or branch == 'fea' else branch }}"
    clone: yes
    update: yes
    accept_hostkey: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone
  register: string_cms-service_admin_backend-scms_version
  notify: debug git clone string_cms-service_admin_backend-scms_version
# chmod -R 700 /root/.ssh/id_rsa
# chmod -R 700 /root/.ssh/id_rsa.pub
# key must be put in root because sudo git clone