--- # 优先次序高
NGINX:
  CONFS:
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/landan-service_backend-lumen/public'
      SERVER_NAME: 'fea.landan.com'
      PHP_VERSION: '5.6'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/landan-admin_backend-lumen/public'
      SERVER_NAME: 'fea.admin.landan.com'
      PHP_VERSION: '7.3'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/cms-service_admin_backend-demososo/'
      SERVER_NAME: 'fea.cms.com'
      REWRITES:
        - '^/404.html /index.php?file=404'
        - '^/index.html /index.php?file=404'
        - '"^/category-([0-9]{1,}).html$" /index.php?routeid=$1&ifalias=n&file=category&page=1'
        - '"^/category-([0-9]{1,})-([0-9]{1,}).html$" /index.php?routeid=$1&ifalias=n&file=category&page=$2'
        - '"^/detail-([0-9]{1,}).html$" /index.php?detailid=$1&ifalias=n&file=category'
        - '"^/tag-([0-9]{1,}).html$" /index.php?routeid=$1&ifalias=n&file=tag&page=1'
        - '"^/tag-([0-9]{1,})-([0-9]{1,}).html$" /index.php?routeid=$1&ifalias=n&file=tag&page=$2'
        - '"^/dmlink-([a-z0-9A-Z_]{1,})-([a-z0-9A-Z_]{1,})-([a-z0-9A-Z_]{1,}).html$" /index.php?file=$1&alias=$2&page=$3'
        - '"^/page-([0-9]{1,}).html$" /index.php?routeid=$1&ifalias=n&file=page&page=1'
        - '^/baidumap.html$ /index.php?routeid=$1&ifalias=n&file=baidumap&page=1'
        - '"^/([a-z0-9A-Z_]{1,}).html$" /index.php?alias=$1&ifalias=y&file=alias&page=1'
        - '"^/([a-z0-9A-Z_]{1,})-([0-9]{1,}).html$" /index.php?alias=$1&ifalias=y&file=alias&page=$2'
      PHP_VERSION: '7.3'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo53-php/'
      SERVER_NAME: 'fea.phpinfo53.com'
      PHP_VERSION: '5.3'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo54-php/'
      SERVER_NAME: 'fea.phpinfo54.com'
      PHP_VERSION: '5.4'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo55-php/'
      SERVER_NAME: 'fea.phpinfo55.com'
      PHP_VERSION: '5.5'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo56-php/'
      SERVER_NAME: 'fea.phpinfo56.com'
      PHP_VERSION: '5.6'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo70-php/'
      SERVER_NAME: 'fea.phpinfo70.com'
      PHP_VERSION: '7.0'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo71-php/'
      SERVER_NAME: 'fea.phpinfo71.com'
      PHP_VERSION: '7.1'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo72-php/'
      SERVER_NAME: 'fea.phpinfo72.com'
      PHP_VERSION: '7.2'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/phpinfo73-php/'
      SERVER_NAME: 'fea.phpinfo73.com'
      PHP_VERSION: '7.3'