---
- name: (service) service kibana restarted
  service:
    name: kibana
    state: restarted
# - name: Debug start nginx
#   debug: 
#     msg: 'The key value is !!'
#   when: debug==true or debug==1
    