---
- name: (template) scp etc/kibana/kibana.yml.j2 /etc/kibana/kibana.yml
  template:
    src: etc/kibana/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: vagrant
    group: vagrant
    mode: 0766