# 安裝 MySQL 5.6 預設 無密碼
---
 
## MYSQL MMM HA monitor 部分
- import_tasks: template-etc_hosts.yml
- import_tasks: yum-install-mysql_mmm.yml
- import_tasks: template-etc_mysql_mmm_mmm_common_conf.yml
- import_tasks: template-etc_mysql_mmm_mmm_mon_conf.yml
- import_tasks: service-mysql_mmm_monitor-restarted.yml
