- name: (file) mkdir /etc/masterha/scripts
  file:
    path: /etc/masterha/scripts
    state: directory
    mode: 0755

- name: "(template) scp etc/masterha/scripts/master_ip_online_change /etc/masterha/scripts/master_ip_online_change"
  template:
    src: etc/masterha/scripts/master_ip_online_change.j2
    dest: /etc/masterha/scripts/master_ip_online_change
    owner: root
    group: root
    mode: 0755