---
- name: "(shell) sudo masterha_check_ssh --conf={{ MASTERHA.CONF }}"
  shell: "masterha_check_ssh --conf={{ MASTERHA.CONF }}"
  register: string_masterha_ssh
- name: (debug) string_masterha_ssh
  debug: 
    msg: "{{ string_masterha_ssh }}"