- import_tasks: pip-install-supervisor.yml
- import_tasks: file-mkdir-etc_supervidor.yml
- import_tasks: file-mkdir-etc_supervidor_conf_d.yml
- import_tasks: template-etc_supervisor_conf_d_default_conf.yml
- import_tasks: template-etc_supervisor_supervisor_conf.yml
- import_tasks: file-mkdir-var_log_supervisord.yml
- import_tasks: file-mkdir-var_log_supervisor.yml
- import_tasks: file-mkdir-var_run_supervisord.yml
# - import_tasks: service-memcached-restarted.yml