- name: (file) rm -Rf /var/log/mysql
  file:
    path: /var/log/mysql
    state: absent
    
- name: (file) mkdir /var/log/mysql
  file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: 0775