---
- name: (yum) yum remove git*
  yum: 
    name: git*
    state: absent
- name: yum install epel-release
  yum:
    name: epel-release
    state: present

- name: (yum) yum insatll ius-release.rpm
  yum: 
    name: https://centos7.iuscommunity.org/ius-release.rpm
- name: (yum) yum install git2u
  yum:
    name: git2u
  notify: debug yum install git