---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
    
- name: (yum) yum install java
  yum:
    name: java
    state: present
  notify: debug yum install java