---
- name: (template) scp etc/nginx/conf.d/default.conf.j2 /etc/nginx/conf.d/*.conf
  template:
    src: etc/nginx/conf.d/default.conf.j2
    dest: "/etc/nginx/conf.d/{{ CONF['SERVER_NAME'] }}.conf"
    owner: root
    group: root
    mode: 0776
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ CHATROOM.NGINX.CONFS }}"
  loop_control:
    loop_var: CONF
  when: chatroom_nginx is not undefined and chatroom_nginx in ['yes', '1', 1, true, True, 'true', 'True', 'nginx']



- name: (service) service nginx restarted
  service:
    name: nginx
    state: restarted
  when: chatroom_nginx is not undefined and chatroom_nginx in ['yes', '1', 1, true, True, 'true', 'True', 'nginx']

# - name: Debug start nginx
#   debug: 
#     msg: 'The key value is !!'
#   when: debug==true or debug==1
    