---
- name: (template) scp tmp/chatroom.js.j2 /tmp/chatroom.js
  template:
    src: tmp/chatroom.js.j2
    dest: /tmp/chatroom.js
    owner: root
    group: root
    mode: 0776
    backup: no
  when: chatroom_mongodb is not undefined and chatroom_mongodb in ['yes', '1', 1, true, True, 'true', 'True', 'mongodb']

- name: (shell) mongo < /tmp/chatroom.js
  shell: mongo < /tmp/chatroom.js
  when: chatroom_mongodb is not undefined and chatroom_mongodb in ['yes', '1', 1, true, True, 'true', 'True', 'mongodb']
  
  
- name: (template) scp tmp/createUser.js.j2 /tmp/createUser.js
  template:
    src: tmp/createUser.js.j2
    dest: /tmp/createUser.js
    owner: root
    group: root
    mode: 0776
    backup: no
  when: chatroom_mongodb is not undefined and chatroom_mongodb in ['yes', '1', 1, true, True, 'true', 'True', 'mongodb']

- name: (shell) mongo < /tmp/createUser.js
  shell: mongo < /tmp/createUser.js
  when: chatroom_mongodb is not undefined and chatroom_mongodb in ['yes', '1', 1, true, True, 'true', 'True', 'mongodb']
