- name: (file) mkdir /var/www/chatroom-service_socket_backend-socketio
  file:
    path: /var/www/chatroom-service_socket_backend-socketio
    recurse: yes  
    owner: root
    group: root
    mode: 0777
  when: chatroom_service_socket_backend_socketio_build is not undefined and chatroom_service_socket_backend_socketio_build in ['yes', '1', 1, true, True, 'true', 'True', 'build']

    
- name: "(git) git clone git@gitlab.ques98.cn:chatroom/chatroom-service_socket_backend-socketio.git /var/www/chatroom-service_socket_backend-socketio"
  git:
    repo: 'git@gitlab.ques98.cn:chatroom/chatroom-service_socket_backend-socketio.git'
    dest: "/var/www/chatroom-service_socket_backend-socketio"
    version: "{{ 'develop' if branch == 'feature' or branch == 'fea' else branch }}"
    update: yes
    accept_hostkey: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone
  when: chatroom_service_socket_backend_socketio_build is not undefined and chatroom_service_socket_backend_socketio_build in ['yes', '1', 1, true, True, 'true', 'True', 'build']
  
  
- name: (template) scp var/www/chatroom-service_socket_backend-socketio/.env.j2 /var/www/chatroom-service_socket_backend-socketio/.env
  template:
    src: var/www/chatroom-service_socket_backend-socketio/.env.j2
    dest: /var/www/chatroom-service_socket_backend-socketio/.env
    owner: root
    group: root
    mode: 0776
    backup: no  
  when: chatroom_service_socket_backend_socketio_build is not undefined and chatroom_service_socket_backend_socketio_build in ['yes', '1', 1, true, True, 'true', 'True', 'build']



- name: "(shell) yarn"
  shell: "cd /var/www/chatroom-service_socket_backend-socketio && yarn"
  when: chatroom_service_socket_backend_socketio_build is not undefined and chatroom_service_socket_backend_socketio_build in ['yes', '1', 1, true, True, 'true', 'True', 'build']

- name: "(shell) yarn run build"
  shell: "cd /var/www/chatroom-service_socket_backend-socketio && yarn run build"
  when: chatroom_service_socket_backend_socketio_build is not undefined and chatroom_service_socket_backend_socketio_build in ['yes', '1', 1, true, True, 'true', 'True', 'build']
  

- name: "(shell) pm2 restart pm2.json"
  shell: "cd /var/www/chatroom-service_socket_backend-socketio && pm2 restart pm2.json"
  when: chatroom_service_socket_backend_socketio_pm2 is not undefined and chatroom_service_socket_backend_socketio_pm2 in ['yes', '1', 1, true, True, 'true', 'True', 'pm2']
  # notify: 
  
  

  
 