---
- name: (template) scp etc/elasticsearch/elasticsearch.yml.j2 /etc/elasticsearch/elasticsearch.yml
  template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0776
