---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
    
- name: (yum) yum install beanstalkd
  yum:
    name: beanstalkd
    state: present
  notify: debug yum install beanstalkd