---
- name: "(shell) sudo masterha_check_repl --conf={{ MASTERHA.CONF }}"
  shell: "masterha_check_repl --conf={{ MASTERHA.CONF }}"
  register: s_masterha_repl
  ignore_errors: yes
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
# - name: (debug) s_masterha_repl
#   run_once: true
#   debug: 
#     msg: "{{ s_masterha_repl }}"