---
- import_playbook: git.yml
  tags:
    - git
- import_playbook: nginx.yml
  tags:
    - nginx
- import_playbook: golang.yml
  tags:
    - golang
- import_playbook: php.yml
  tags:
    - php
 - import_playbook: node.yml
   tags:
     - node
- import_playbook: redis.yml
  tags:
    - redis
- import_playbook: beanstalkd.yml
  tags:
    - beanstalkd
- import_playbook: mysql.yml
  tags:
    - mysql
- import_playbook: mongodb.yml
  tags:
    - mongodb
