---
- name: Install feature mongodb
  hosts: fea-mongodb
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook mongodb starts'
  roles:
    - role: mongodb
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook mongodb ends'
- name: Install develop mongodb
  hosts: fea-mongodb
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook mongodb starts'
  roles:
    - role: mongodb
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook mongodb ends'
